@hostname = http://localhost
@port = 3001
@host = {{hostname}}:{{port}}

###

GET {{host}}/api/flightscanner/airports

###


POST {{host}}/api/flightscanner/airports
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphdmlyQCIsImlhdCI6MTY4MzM3MDQ2OH0.YSx19LA2ciORDfKKGQZUn9dIo0iFpd3ESMaCpdZdBJw

{
    "nombre": "Aeropuerto Internacional de Magallanes",
    "distancia_ciudad": 13,
    "transportes": ["Metro", "Autobús", "Taxi"],
    "servicios": ["restaurantes", "tiendas", "wifi"]
}
