@hostname = http://localhost
@port = 3001
@host = {{hostname}}:{{port}}

GET {{host}}/api/flightscanner/customers

###

GET {{host}}/api/flightscanner/airports


###

POST {{host}}/api/flightscanner/airports
Content-Type: application/json

{
    "nombre": "Aeropuerto Internacional de Málaga",
    "distancia_ciudad": 13,
    "transportes": ["Metro", "Autobús", "Taxi"],
    "servicios": ["restaurantes", "tiendas", "wifi"]
}

###

GET {{host}}/api/flightscanner/flights

###

POST {{host}}/api/flightscanner/customers
Content-Type: application/json

{
    "nombre": "Dani",
    "apellidos": "Funes",
    "contraseña": "123456",
    "email": "daniel@",
    "numero_pasaporte": "454544555A"
}


